.gitignore, Project.toml, src/LinearSolve.jl, src/common.jl, src/default.jl, src/factorization.jl, src/krylov.jl, src/wrappers.jl, test/ode_test.jl, test/runtests.jl
TODO
ref https://github.com/SciML/LinearSolve.jl/issues/3
=> LinearSolve interface

src/common.jl, src/default.jl, src/factorization.jl, test/runtests.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/7
=> Fix default solve algorithm handling

src/common.jl, src/wrappers.jl, test/runtests.jl
move abstol, reltol, maxiters, vebose to cache from wrappers.
ref https://github.com/SciML/LinearSolve.jl/issues/23
=> common arg handling

src/default.jl
Because this is GPU-compatible. IterativeSolvers.jl does some low rank Q updating which might make it more efficient on CPU but precludes it from being used on the GPU, so if that's the case then we use IterativeSolvers for the speed but more generally fall back to Krylov.jl
=> Change default to use KrylovJL_GMRES on non Array

src/common.jl, src/pardiso.jl, test/runtests.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/38
=> Fix default tolerance for complex

src/iterative_wrappers.jl, test/runtests.jl
https://github.com/SciML/LinearSolve.jl/issues/70 shows that setting the initial condition in GMRES is a minefield. Currently it's pretty much impossible for any user to guess correctly so pretty much any case would do better with resetting to zero. The papers suggest doing that even if the rescaling is done in many cases, and the tests require it. So for the sanity of everyone, I think it's best to reset to zero, and if the rescaling is implemented this can be removed, but until then keeping it hardcoded is a good idea.
=> Auto-reset GMRES u to zero

src/factorization.jl
Unless you need it to operate in-place, it would probably make more sense to use the 3-arg `ldiv!` everywhere
=> Use 3-arg `ldiv!`

src/pardiso.jl
The defaults are not safe if the values of `A` are not in the correct scaling, which is only safe if the values are not changing often or you re-analyze. So this sets it up to be safe and fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1569
=> Fix Pardiso analysis saving

LICENSE, src/LinearSolve.jl, src/default.jl, src/factorization.jl, src/simplelu.jl
```julia
using OrdinaryDiffEq, ParameterizedFunctions, BenchmarkTools
using LinearSolve
f = @ode_def Orego begin
dy1 = p1*(y2+y1*(1-p2*y1-y2))
dy2 = (y3-(1+y1)*y2)/p1
dy3 = p3*(y1-y3)
end p1 p2 p3
p = [77.27,8.375e-6,0.161]
prob = ODEProblem(f,[1.0,2.0,3.0],(0.0,30.0),p)
solve(prob,Rosenbrock23(),abstol=1e-6,reltol=1e-6)
@btime solve(prob,Rosenbrock23(linsolve=GenericLUFactorization()),abstol=1e-6,reltol=1e-6)
@btime solve(prob,Rosenbrock23(linsolve=RFLUFactorization(),chunk_size = Val{3}()),abstol=1e-6,reltol=1e-6)
```
=> add GenericLUFactorizations

src/common.jl
This should fix https://github.com/SciML/LinearSolve.jl/issues/101. I'm not sure if the `zero.` is necessary here, it adds an allocation but there could be some solver sensitive to garbage in the result vector?
=> Nonsquare matrix fix

src/preconditioners.jl, test/basictests.jl
Reverts SciML/LinearSolve.jl#100
Apparently this is used in the Arnoldi implementation of IterativeSolvers.
https://buildkite.com/julialang/ordinarydiffeq-dot-jl/builds/894#02c3fa19-ab47-4ee0-9207-cbdde9fd3bb7/398-852
https://github.com/SciML/OrdinaryDiffEq.jl/runs/5034980953?check_suite_focus=true#step:6:461
@ranocha @vpuri3
=> Revert "avoid ldiv of invpreconditioner"

src/factorization.jl
https://github.com/JuliaLang/julia/issues/17670
=> Only fill the nonzeros

src/common.jl
https://github.com/SciML/LinearSolve.jl/blob/main/src/iterative_wrappers.jl#L102-L103
https://github.com/SciML/LinearSolve.jl/blob/main/src/iterative_wrappers.jl#L205
=> fix outdated comment

Project.toml, src/LinearSolve.jl, src/factorization.jl, test/basictests.jl
This is just a basic set of functions I was able/willing to develop on my laptop at sea. I've only tested `A*x \approx b` for those factorizations right now. 
I'll add tests shortly. A few questions:
1. Should we default to this workspace system for QR and LU? Rather than having "FastQRFactorization"
2. Should the workspace be resized when a user uses `set_A` with a different size matrix? Problematically I triggered a segfault once when playing with the sizing of A this evening, so I'll have to track that down. It's supposed to just error (and mostly does). FastLAPACKInterface.jl doesn't provide a method to resize workspaces as far as I can tell.
=> FastLAPACK

src/factorization.jl
Otherwise it's just using the values from before!
BTW, why do we need to klu_factor before klu!, instead of just klu!? Don't that do the factorization as well?
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1701
=> update values before klu_factor

src/default.jl
Summary:
- RecrusiveFactorization choice looks for Flaot32|Float64 and Julia threads. This should fix the main issue in https://github.com/SciML/LinearSolve.jl/issues/159 that RFLUFactorization is not optimized on complex matrices
- CuArrays now supports LU factorizations
- If a standard matrix, then use FastLUFactorization
That last bit still has a question mark (https://github.com/SciML/LinearSolve.jl/issues/159#issuecomment-1186526040)
=> Many tweaks to the default algorithm choice

src/default.jl
Given the benchmarks with @chriselrod and @YingboMa, it seems there is some point where a cutoff to UMFPACK makes sense. I'm placing it at 10_000 for now as a reasonable guess because we're very sure that <10_000 is bad for UMFPACK, but this should get a bit more tuning in the future. It should also depend on whether someone is using OpenBLAS or not.
=> Improve default sparse solver choice

src/default.jl
https://github.com/SciML/PreallocationTools.jl/pull/30#issuecomment-1211427322
=> only use LU for CUDA when v1.8+

docs/src/basics/FAQ.md, docs/src/basics/Preconditioners.md
I see `IterativeSolvers_GMRES` written at places in docs, while what works for me is `IterativeSolversJL_GMRES`. Is that a typo?
=> Is it a typo?

docs/make.jl, lib/LinearSolvePardiso/src/LinearSolvePardiso.jl, src/common.jl, src/default.jl, src/factorization.jl, src/iterative_wrappers.jl, src/simplelu.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/177
=> Add an assumptions mechanism for type-stable default help, and nonsquare

docs/src/advanced/custom.md, docs/src/basics/FAQ.md, docs/src/basics/Preconditioners.md, docs/src/tutorials/caching_interface.md, docs/src/tutorials/linear.md
Fixes https://github.com/SciML/LinearSolve.jl/issues/186
=> example blocks

src/LinearSolve.jl, src/default.jl, src/factorization.jl, src/iterative_wrappers.jl, test/nonsquare.jl, test/runtests.jl
Is there any better choice with no other information a priori?
=> Default non-square operators to LSMR

src/factorization.jl, test/basictests.jl, test/zeroinittests.jl
@ChrisRackauckas acceptable? I'll add a check option to UMFPACK for 1.9, and figure out how I want to do this in KLU. But this should suffice for now, we can always set `check = false` default later once those checks are integrated upstream.
=> Simple quick fix for refactor issue

src/LinearSolve.jl
There is a small probability that the current choice is singular which causes a precompilation error.
=> Avoid singular A during precompilation

src/iterative_wrappers.jl, test/basictests.jl
This tries to remove the error on KrylovKit iterative solver. 
I am not sure why but this does not work because of a Rosetta issue on my computer.
Basically, the way to trigger CG is to pass `isposdef = true` to KrylovKit.
=> correct mistake in constructor of KrylovKitJL

.github/workflows/DocsPreviewCleanup.yml, docs/make.jl
- preview cleanup CI taken from MuladdMacro.jl
- enable preview
- remove analytics
=> doc cleanup prototype

docs/src/solvers/solvers.md, src/LinearSolve.jl, src/default.jl, src/factorization.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/219, though we'll need to continue to figure out why it's not eliding the allocation of the solution struct.
=> Specialize diagonal matrices

src/iterative_wrappers.jl
Prevents these warnings:
┌ Warning: cg! doesn't support right preconditioning.
└ @ LinearSolve ~/.julia/packages/LinearSolve/fBayl/src/iterative_wrappers.jl:168
=> fix typo when setting Pr to default

lib/LinearSolvePardiso/Project.toml, lib/LinearSolvePardiso/src/LinearSolvePardiso.jl, lib/LinearSolvePardiso/test/runtests.jl, src/LinearSolve.jl, src/default.jl, src/factorization.jl
This e.g. would allow to supply a matrix type with multithreaded factorization etc. Would solve #190. 
However, see https://github.com/JuliaSparse/SparseArrays.jl/issues/265 .
=> Use AbstractSparseMatrixCSC for sparse factorizations

docs/make.jl, docs/src/advanced/custom.md, docs/src/basics/FAQ.md, docs/src/basics/Preconditioners.md, docs/src/solvers/solvers.md
Without `linkcheck=true` the strict doc build will never fail.
=> strict links

lib/LinearSolveCUDA/Project.toml, lib/LinearSolveCUDA/src/LinearSolveCUDA.jl, lib/LinearSolvePardiso/Project.toml, lib/LinearSolvePardiso/src/LinearSolvePardiso.jl
There isn't a perfectly nice way to do this, but this seems reasonable to add after the release is out.
=> Deprecate the extra libs

docs/src/basics/common_solver_opts.md, src/common.jl
This patch documents that `alias_A` and `alias_b` may depend on whether
the algorithm is known not to modify `A` or `b`. As a minimal first
change, this patch updates the default value for
`alg::AbstractKrylovSubspaceMethod` from `false` to `true`.
=> Update documentation regarding alias behavior

docs/make.jl, docs/pages.jl, docs/src/advanced/developing.md, docs/src/basics/FAQ.md, ext/LinearSolveCUDAExt.jl, ext/LinearSolveHYPREExt.jl, ext/LinearSolveIterativeSolversExt.jl, ext/LinearSolveKrylovKitExt.jl, ext/LinearSolvePardisoExt.jl, src/LinearSolve.jl, src/common.jl, src/default.jl, src/deprecated.jl, src/extension_algs.jl, src/factorization.jl, src/factorization_sparse.jl, src/iterative_wrappers.jl, src/simplelu.jl, src/solve_function.jl, test/basictests.jl, test/default_algs.jl, test/hypretests.jl, test/nonsquare.jl, test/pardiso/pardiso.jl, test/resolve.jl
It won't handle adjoint but that makes it error even when its not used from the default choice, and so this makes it so the defaults don't error. Past v1.7 it's not needed.
=> workaround Cholesky factorization limitations on v1.6

src/iterative_wrappers.jl
This solves https://github.com/SciML/LinearSolve.jl/issues/297. KrylovKit.jl already throws `ReturnCode.Failure` if it doesn't converge, IterativeSolvers.jl doesn't have it possible, and now Krylov.jl is using retcodes. So now nothing is silent on non-convergence when it's possible to be known from the solver. This also fixes https://github.com/SciML/LinearSolve.jl/issues/298
=> Setup retcode for Krylov.jl

src/default.jl, test/default_algs.jl
Closes https://github.com/SciML/LinearSolve.jl/issues/340. While many results are very much based on more details about the sparsity pattern, it's at least clear that if the matrix is not very sparse then it should probably use UMFPACK, so this is a conservative bound. When mixed with the length bound, I find that this seems to work rather well, though is not always optimal, is at least better than always choosing UMFPACK
=> Set a sparsity threshold for KLU

src/iterative_wrappers.jl, test/basictests.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/347
=> Fiox solution handling for KrylovJL on subarrays

benchmarks/lu.jl
Same as https://github.com/SciML/SciMLBenchmarks.jl/pull/623
=> Add a standard LU performance benchmark

src/LinearSolve.jl, src/init.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/353
=> Consolidate init

benchmarks/sparselu.jl
=> Add sparselu benchmark

src/LinearSolve.jl
This captures all of the issues introduced by SparseArrays and LoopVectorization and starts us afresh. The precompile time change is not noticable.
=> Recompile invalidations post LoopVectorization

src/LinearSolve.jl, src/appleaccelerate.jl, src/default.jl
The benchmarks show that it's just so much better, and there's no cost to doing this, so we should just always use AppleAccelerate on any machine where it exists.
=> Make AppleAccelerate the default algorithm when available

Project.toml, src/LinearSolve.jl, src/default.jl, src/factorization.jl, test/nonsquare.jl
Makes the following changes:
* New `needs_square_A` trait for solvers
* For underdetermined systems, we automatically use Pivoted QR similar to Base
=> Add `needs_square_A` trait

ext/LinearSolveEnzymeExt.jl
Fixes bug when using LinearSolve (cc @wsmoses)
```julia
ERROR: LoadError: UndefVarError: `AbstractKrylovSubspaceMethod` not defined
Stacktrace:
[1] #reverse#22
@ ~/.julia/packages/LinearSolve/sUzK0/ext/LinearSolveEnzymeExt.jl:147
[2] reverse
@ ~/.julia/packages/LinearSolve/sUzK0/ext/LinearSolveEnzymeExt.jl:132 [inlined]
[3] #solve#83
@ ./deprecated.jl:105
[4] solve
@ ./deprecated.jl:103
[5] Solverx
@ ~/Dartmouth/dJUICE/src/core/toolkits.jl:212
[6] Solverx
@ ~/Dartmouth/dJUICE/src/core/toolkits.jl:199 [inlined]
[7] solutionsequence_nonlinear
@ ~/Dartmouth/dJUICE/src/core/solutionsequences.jl:53
[8] Core
@ ~/Dartmouth/dJUICE/src/core/analyses/stressbalanceanalysis.jl:114
[9] costfunction
@ ~/Dartmouth/dJUICE/src/core/solve.jl:70 [inlined]
[10] diffejulia_costfunction_3853wrap
@ …
```
=> [EnzymeExt] Prefix AbstractKrylovSubspaceMethod to avoid undefvarerror

ext/LinearSolveEnzymeExt.jl, src/default.jl, test/enzyme.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/403
=> handle the default algorithm with enzyme adjoints

src/default.jl
@ChrisRackauckas I saw that this was done for MKL in #390, but it seems to be missing for AppleAccelerate. Is this the correct way to handle it?
=> Don't use AppleAccelerate on number types that are not floats

Project.toml, src/LinearSolve.jl, src/factorization.jl, src/factorization_sparse.jl
We remove SuiteSparse as it has now been merged with SparseArrays.
=> Remove SuiteSparse

Project.toml, ext/LinearSolveFastAlmostBandedMatricesExt.jl, src/factorization.jl, test/banded.jl
It depends on an unreleased package. I will cleanup that package and release it soon.
=> Add support for almost banded matrix

ext/LinearSolveBandedMatricesExt.jl, ext/LinearSolveFastAlmostBandedMatricesExt.jl, src/default.jl, src/factorization.jl
Fixes many of the method ambiguities in this package.
Things I'm still unsure about:
First, for `defaultalg` there is dispatch for `AbstractSciMLOperator` as well as dispatch for `OperatorAssumptions{Nothing}`.
`AbstractSciMLOperator` dispatches based on `A.A`.
`OperatorAssumptions{Nothing}` dispatches based on `issquare(A)`.
If both occur together, I don't know which order to apply them.
Currently, it first gets rid of the `Nothing`, but this means `issquare` has to be defined for `Operators`.
Second, there are remaining ambiguities regarding:
```julia
function init_cacheval(alg::GenericFactorization,
A::Union{Hermitian{T, <:SparseMatrixCSC},
Symmetric{T, <:SparseMatrixCSC}}, b, u, Pl, Pr,
maxiters::Int, abstol, reltol, verbose::Bool,
assumptions::OperatorAssumptions) where {T}
newA = …
```
=> start fixing ambiguities

src/LinearSolve.jl, src/default.jl, src/iterative_wrappers.jl, test/default_algs.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/414
=> Fix and test solvers for non-square operators

src/factorization.jl
All are supposed to be run with check=false
=> Disable error throwing in RFLU

docs/src/basics/Preconditioners.md
Adds KrylovPreconditioners.jl and fixes a typo in the AlgebraicMultigrid.jl refernce
=> Update preconditioner docs

src/default.jl
Base's type printing code uses the REPL's currently active module to determine how to print types. Unfortunately, this means it is illegal to use this in generated functions. Switch to grabbing the symbol directly from the typename, since this now errors on julia master:
```
Got exception outside of a @test
LoadError: MethodError: no method matching active_module()
You may have intended to import Base.active_module
The applicable method may be too new: running in world age 26446, while current world is 26576.
Closest candidates are:
active_module(::REPL.LineEditREPL) (method too new to be called from this world context.)
@ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:590
active_module() (method too new to be called from this world context.)
@ REPL …
```
=> Don't use type-printing from inside a generated function

Project.toml, src/LinearSolve.jl, src/appleaccelerate.jl, src/init.jl
See discussion in https://github.com/SciML/SciMLBenchmarks.jl/pull/858
=> Check appleaccelerate is available in __init__

src/factorization.jl, test/default_algs.jl
This prevents singular exceptions.
=> Fix `UMFPACK` to use `check=false`

ext/LinearSolveCUDAExt.jl, src/factorization.jl, src/factorization_sparse.jl
This should fix the LE issue and make the diffs readable again.
=> Fix the formatting

Project.toml, src/factorization.jl
Sorry for the bad diff, there was a bad windows code that was merged which changed all the line endings
* Fixes QR for symmetric matrices
* LU also early terminates now (not sure why we have 2 copies of `solve!` and `do_factorization`, which can be merged together with a different abstraction?)
Let's wait for https://github.com/SciML/NonlinearSolve.jl/pull/414 to be finished.
=> Handle LU failure and Symmetric QR

src/iterative_wrappers.jl, test/retcodes.jl, test/runtests.jl
Trying to resolve #507 . However, this is technically a breaking change.
Also, the factorization solvers should set their retcode to Success and not to Default, or am I missing something? Because `SciMLBase.successful_retcode(ReturnCode.Default) == false` .
=> Fix returncodes and stats for iterative solvers

src/LinearSolve.jl
`@recompile_invalidations` should only be used in very specific scenarios, and this is not one of those scenarios. Also, there are big changes being done with https://github.com/SciML/CommonWorldInvalidations.jl. With that, we only need to `@recompile_invalidations` on a few entry points. In particular, Static.jl, Symbolics.jl, and preferably ForwardDiff.jl and StaticArrays.jl would adopt it too. But this means that in order to handle all of this effectively, in SciML we only need to apply it on Static.jl, Symbolics.jl, and SciMLBase.jl and the whole ecosystem should be fine.
In any case, this library doesn't need it. It shouldn't make a tangible difference in compile times, while it increases precompile times by a lot.
=> Remove recompile_invalidations

Project.toml, src/LinearSolve.jl, test/qa.jl
This fixes LinearSolve on AArch64, for example.
=> Import CpuId only on x86_64 or i686

src/common.jl, test/basictests.jl
* `SciMLBase.init` did check only for `SparseMatrixCSC`, thus leading to  dispatches for AbstractSparseMatrixCSC with awful timings.
* Now, if A (resp. b) is an `AbstractSparseMatrixCSC`, instead of making a `copy` (or even `deepcopy`), a `SparseMatrixCSC` is constructed using `size`, `getcolptr`, `rowvals` and `nonzeros`.
=> Fix handling of AbstractSparseMatrixCSC

src/LinearSolve.jl, src/common.jl, src/factorization.jl, test/basictests.jl, test/resolve.jl
Both are subtypes of AbstractFactorization.
This allows to set default_alias_A=true for sparse factorizations (which just cannot overwrite A anyway). This allows to create the cache parametrized with the original matrix type and we can use `reinit!(cache;A)` or `cache.A=A` if `A` is an AbstractSparseMatrixCSC, like with Krylov solvers.
Before, due to https://github.com/SciML/LinearSolve.jl/pull/525, these methods would require a SparseMatrixCSC, even if the Problem was created with a AbstractSparseMatrixCSC.
=> Introduce AbstractSparseFactorization and AbstractDenseFactorization

ext/LinearSolveHYPREExt.jl, ext/LinearSolveIterativeSolversExt.jl, src/common.jl, src/iterative_wrappers.jl, test/basictests.jl
alternative to https://github.com/SciML/LinearSolve.jl/pull/535, fixes https://github.com/SciML/LinearSolve.jl/issues/527 for real this time. I don't love this answer, but I think it is the easiest way for now.
=> use isfresh like mechinisim for precs

ext/LinearSolvePardisoExt.jl, src/extension_algs.jl, test/pardiso/pardiso.jl
=> Fix Pardiso extension for the case of an AbstractSparseMatrixCSC

src/LinearSolve.jl, src/iterative_wrappers.jl, test/basictests.jl
A very minor change to add the minares solver from `Krylov.jl` to the iterative wrappers. The paper can be found [here](https://arxiv.org/abs/2310.01757)
=> Add MinAres solver to iterative wrappers

docs/src/advanced/developing.md
Fixes issues in the documentation found while wiring up some Dagger integrations. Hopefully all of these changes make sense, I'm not 100% sure if everything I'm doing here is the correct way to do things (these were gleaned by reading the code).
=> docs: Fixes for solver developing information

ext/LinearSolveSparseArraysExt.jl, src/LinearSolve.jl, src/iterative_wrappers.jl
Just fixing the typo in the function name.
=> fix typo: makeempty_SparaseMatrixCSC -> makeempty_SparseMatrixCSC

docs/src/tutorials/accelerating_choices.md, ext/LinearSolveSparspakExt.jl, src/KLU/klu.jl, src/iterative_wrappers.jl
=> Fix sparspak init_cacheval

.github/workflows/Tests.yml, ext/LinearSolveSparseArraysExt.jl, src/default.jl, src/factorization.jl, test/defaults_loading.jl, test/runtests.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/578#issuecomment-2732360172
=> Throw proper error for Sparspak missing

Project.toml, ext/LinearSolveSparseArraysExt.jl, test/basictests.jl
The test
```julia
@testset "Sparse matrix (check pattern_changed)" begin
n = 4
A = spdiagm(1 => ones(n - 1), 0 => fill(2.0, n), -1 => ones(n - 1))
b = rand(n)
linprob = @inferred LinearProblem(A, b)
alg = @inferred LUFactorization()
linsolve = @inferred init(linprob, alg)
linres = @inferred solve!(linsolve)
end
```
I added failed before with the error
```
Error During Test at REPL[52]:1
Got exception outside of a @test
ArgumentError: pattern of the matrix changed
Stacktrace:
[1] umferror(status::Int32)
@ SparseArrays.UMFPACK
[...]
```
I already bumped the patch version to make it …
=> fix `pattern_changed`

docs/src/tutorials/accelerating_choices.md
Pure documentation change: The link to the performance comparison in the "sparse solvers" section showed the same image from the "dense solvers" section.
The plot titles are a bit cropped, but I think it's still more informative to show the data that is referenced in the text on the page.
(If understood the guidelines for contributing correctly, none of the points on the checklist below apply here.)
=> Fix linked image in accelerating_choices.md

docs/pages.jl, docs/src/tutorials/accelerating_choices.md, docs/src/tutorials/gpu.md, docs/src/tutorials/linear.md, src/factorization.jl
https://discourse.julialang.org/t/what-is-a-recommended-way-to-solve-a-linear-equation
=> Address comments of Discourse

src/adjoint.jl, src/default.jl
This can't be easily tested because it's very architecture-dependent, but it fixes https://github.com/SciML/LinearSolve.jl/issues/601
=> Fix default adjoint for AppleAccelerate and MKL

docs/src/tutorials/linear.md
@WalterMadelim did some edits, did this cover all the questions you had?
=> More updates to the Getting Started page

ext/LinearSolveSparseArraysExt.jl, ext/LinearSolveSparspakExt.jl, src/LinearSolve.jl, test/default_algs.jl
Part 2 of fixes https://github.com/SciML/NonlinearSolve.jl/issues/599
=> Fix non-square sparse matrix preallocations for defaults

ext/LinearSolveSparseArraysExt.jl
Type variable T not used in `init_cacheval` method, so removed
- [x ] Appropriate tests were added
- [x ] Any code changes were done in a way that does not break public API
- [x ] All documentation related to code changes were updated
- [x ] The new code follows the
- [ x] Any new documentation only uses public API
=> Remove type variable T

docs/src/solvers/solvers.md, src/LinearSolve.jl, src/default.jl, test/default_algs.jl, test/retcodes.jl
In action:
```julia
using LinearSolve
A = [1.0 0 0 0
0  1 0 0
0  0 1 0
0 0 0 0]
b = rand(4)
prob = LinearProblem(A, b)
sol = solve(prob, LinearSolve.DefaultLinearSolver(LinearSolve.DefaultAlgorithmChoice.LUFactorization; safetyfallback=false))
@test sol.retcode === ReturnCode.Failure
@test sol.u == zeros(4)
sol = solve(prob)
@test sol.u ≈ svd(A)\b
```
Previously it would just fail, now it falls back to the column-pivoted QR in order to successfully factorize when necessary.
=> Add column-pivoted QR factorization fallback on failed LU factorization

.buildkite/pipeline.yml, ext/LinearSolveCUDAExt.jl, ext/LinearSolveSparseArraysExt.jl, src/LinearSolve.jl, test/gpu/Project.toml, test/gpu/cuda.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/625
=> Fix CUDSS dispatches

src/appleaccelerate.jl, src/mkl.jl
For `appleaccelerate` and `mkl`, the `fact` variable is a tuple, only the first element should be checked.
I think these cases must not be covered in your test suite, but I was getting the following error:
```
ERROR: MethodError: no method matching issuccess(::Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Base.RefValue{Int64}})
The function `issuccess` exists, but no method is defined for this combination of argument types.
Closest candidates are:
issuccess(::LinearAlgebra.BunchKaufman)
@ LinearAlgebra ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/LinearAlgebra/src/bunchkaufman.jl:321
issuccess(::StaticArrays.LU)
@ StaticArrays ~/.julia/packages/StaticArrays/LSPcF/src/lu.jl:71
issuccess(::SparseArrays.CHOLMOD.Factor)
@ SparseArrays …
```
=> Fix check of factorisation

src/common.jl, test/retcodes.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/633
=> Fix retcodes on staticarray overloads

ext/LinearSolveCUDAExt.jl
=> Fix LinearSolveCUDAExt.jl

src/factorization.jl
Hi there,
I was working with the pattern memory-saving options in LinearSolve.jl and found the documentation a bit confusing. I have proposed a clarification based on how the current keyword arguments behave.
Have a nice evening!
Marieke
FYI: @j-fu
=> Fix docstring of UMFPACKFactorization and KLUFactorization

src/common.jl, test/forwarddiff_overloads.jl
We should check to make sure that the ForwardDiff overloads don't apply to StaticArrays.
=> Add test for ForwardDiff with StaticArrays 

Project.toml, ext/LinearSolveBLISExt.jl
Based on #431, this demonstrates how to get the BLIS extension working using `libblastrampoline` combined with `LAPACK_jll` (based on Reference LAPACK 3.11 https://github.com/Reference-LAPACK/lapack/releases/tag/v3.11)
Note that `suffix_hint="64_",` in `BLAS.lbt_forward` enables ILP versions.
=> Enable "WIP: Wrap BLIS" with reference LAPACK

src/appleaccelerate.jl
```julia
Enzyme Derivative Rules: Error During Test at /home/runner/.julia/packages/SafeTestsets/raUNr/src/SafeTestsets.jl:30
Got exception outside of a @test
LoadError: could not load library "/System/Library/Frameworks/Accelerate.framework/Accelerate"
/System/Library/Frameworks/Accelerate.framework/Accelerate.so: cannot open shared object file: No such file or directory
Stacktrace:
[1] fix_ptr_lookup(name::String)
@ Enzyme.Compiler.JIT ~/.julia/packages/Enzyme/LMVya/src/compiler/orcv2.jl:63
[2] add!(mod::LLVM.Module)
@ Enzyme.Compiler.JIT ~/.julia/packages/Enzyme/LMVya/src/compiler/orcv2.jl:251
[3] _link(job::GPUCompiler.CompilerJob{<:Enzyme.Compiler.EnzymeTarget}, mod::LLVM.Module, edges::Vector{Any}, adjoint_name::String, primal_name::Union{Nothing, String}, TapeType::Any, …
```
=> Safety measures around AppleAccelerate

ext/LinearSolveForwardDiffExt.jl, src/common.jl, test/forwarddiff_overloads.jl
Needed so that GenericalLUFactorization on DualLinearProblems can go through the normal init. 
It's a little bit clunky but I don't think there's another way to exclude specific algorithms from going through the Dual version of `init`. Plus this way is explicit about exactly which algorithms will go through the Dual overloads.
=> Make `GenericLUFactorization` bypass overloads when used on DualLinear Problems

ext/LinearSolveForwardDiffExt.jl
Trying to address https://github.com/SciML/OrdinaryDiffEq.jl/issues/2837 and https://github.com/SciML/LinearSolve.jl/issues/648
This gets rid of the call to `deepcopy`.
This also puts the type of the dual number that needs to be constructed in to the type system instead of having it be a field in the dual caches. I'm not sure if that will help with trimming but I think in general it's a better way to do this.
=> Get rid of `deepcopy`, put Dual types in type system 

test/pardiso/pardiso.jl
* prevent soft scope warning in 1.12
* slightly relax accuracy for current panua pardiso
* ran locally with both MKL and Panua
* tested locally with https://github.com/JuliaSparse/Pardiso.jl/pull/117 which introduces finalizers
=> Cleanup pardiso test

src/appleaccelerate.jl
Fixes a big performance regression
=> Fix performance of AppleAccelerate check for Enzyme

ext/LinearSolveForwardDiffExt.jl, test/nopre/jet.jl
=> Make length of Partials known at compile time in ForwardDiff overloads

docs/src/solvers/solvers.md
The old doc was likely a typo or copy-pasta.
=> Replace Krylov_{CG,GMRES} by KrylovJL_{CG,GMRES}

src/mkl.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/787
=> Make MKL check to be fully static

src/LinearSolve.jl, src/mkl.jl, src/openblas.jl
The is_available checks should be runtime checks, which will be possible
to handle fully properly once MKL_jll and OpenBLAS_jll are upgraded to
support that. For now, just convert the variables here so that they
aren't trying to do a runtime lookup of a module that was not imported.
This is required for the package to continue working once ccall syntax correctness verification is enabled (https://github.com/JuliaLang/julia/pull/59165)
=> prepare to properly suppory lazy libraries

ext/LinearSolveForwardDiffExt.jl, test/nopre/jet.jl
=> Performance fixes for DualLinearProblems

src/LinearSolve.jl
Tries to safeguard https://github.com/julia-actions/setup-julia/pull/300 https://github.com/JuliaLang/julia/issues/55878 where the user has requested an incorrect architecture and thus we may believe we can load MKL until we check `MKL_jll.is_available() == false`. The reason is because we're being lied to about `@static if Sys.ARCH === :x86_64 || Sys.ARCH === :i686` which then makes it take this branch and then MKL does not exist. We could instead check `isapple` another type of workaround here and 99% of users would be perfectly fine, but if this is safe this is slightly better for the 1 remaining Intel Apple user that exists in the wild somewhere.
=> Better safeguard on unloadable MKL

src/LinearSolve.jl
This should make https://github.com/SciML/LinearSolve.jl/issues/790 a lot less likely
=> Give a very clear and strong error message for 64-bit builds with 32-bit BLAS

ext/LinearSolveForwardDiffExt.jl, test/forwarddiff_overloads.jl, test/nopre/jet.jl
This makes it so that the default alg is chosen based on the primal A and b _before_ going to make the Dual cache. This also means that for small problems GenericLU will be used, and the cache will be a normal LinearCache.
=> Fix handling for default algorithms for DualLinearProblems
