- src/LinearSolve.jl
- src/factorization.jl
- test/runtests.jl
ref https://github.com/SciML/LinearSolve.jl/issues/4
> RecursiveFactorization.lu!

- src/default.jl
- src/factorization.jl
- test/runtests.jl
LU was not previously working for `SparseMatrixCSC` and tests were not being run due to a variable name typo in several places.
> Correct UMFPACK and test proper variables

- Project.toml
- src/LinearSolve.jl
- src/common.jl
- src/wrappers.jl
- test/runtests.jl
TODO
Fix https://github.com/SciML/LinearSolve.jl/issues/26
> default preconditioners

- Project.toml
- src/LinearSolve.jl
- src/factorization.jl
- test/runtests.jl
This implementation dives a little deep into the guts of UMFPACK, but I suppose that's probably inevitable. I don't believe there's a good way to check that pattern(A1) == pattern(A2), so it just throws right now.
> Initial pass at storing symbolic factorization

- Project.toml
- src/factorization.jl
See https://github.com/JuliaLang/julia/issues/33143 for more details
> hotfix: manually call 2-argument ldiv! to avoid resize! problems

- src/preconditioners.jl
- test/basictests.jl
closes https://github.com/SciML/LinearSolve.jl/issues/97
> avoid ldiv of invpreconditioner

- test/basictests.jl
just making sure default alg works for diagonal. isolating https://github.com/SciML/LinearSolve.jl/issues/110 error to ordinarydiffeq
> diagonal test

- docs/src/solvers/solvers.md
Remove claim of improved performance for complex matrices.  Ref #159
> Correct documentation for `RFLUFactorization`

- src/factorization.jl
- test/basictests.jl
> Fix UMFPACK no symbolic factorization branch

- src/factorization.jl
Fixes #205 
This won't work quite yet, waiting on 1.9 upstream
> Use new ctor in 1.9

- .github/workflows/CompatHelper.yml
Also check the docs/Project.toml file.
> prototype doc compat

- docs/src/basics/Preconditioners.md
This matches sundials docs and I checked if in the implementation it was passed like this to Krylov.jl
> [skip ci] fix preconditioner documentation

- README.md
- src/LinearSolve.jl
- src/default.jl
- src/factorization.jl
* set default algorithm to sparspak for generic float
* precompile sparspak
* Mention sparspak in README
> More on sparspak

- Project.toml
- src/LinearSolve.jl
Fixed bug occuring with structurally unsymmetric matrices in https://github.com/PetrKryslUCSD/Sparspak.jl/commit/2b5b685895abdf693a7f72f5903ff87be0bc83b5
> Update Sparspak to 0.3.6

- src/factorization.jl
It's really slow, see https://github.com/SciML/LinearSolve.jl/issues/283
> Don't use qr! on SparseMatrixCSC

- ext/LinearSolveHYPRE.jl
I cannot test this locally, but if CI passes then :+1: it should be good.
> Fix HYPRE Solution Building

- src/factorization.jl
- test/nonsquare.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/287
> Fix non-square sparse views

- docs/src/solvers/solvers.md
- test/sparse_vector.jl
> Fix some typos

- docs/pages.jl
- docs/src/release_notes.md
- src/LinearSolve.jl
- src/factorization.jl
Fix precompilation, requires the `@generated` function move until after the defaults are all defined. A bit ehh, but it works.
> Re-enable some precompilation

- src/deprecated.jl
> Fix deprecation

- src/factorization.jl
- test/default_algs.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/326
> Fix and better test UMFPACK default

- .github/workflows/CI.yml
- src/LinearSolve.jl
- src/factorization.jl
- test/basictests.jl
- test/default_algs.jl
- test/resolve.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/330
> Fix check checking on previous Julia versions

- Project.toml
- src/factorization.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/335
> Fix QR initializations with pivoting

- src/LinearSolve.jl
- test/traits.jl
so we can deprecate diffeqoperators.
Please bump version after merging.
> rm diffeqidentity

- ext/LinearSolveEnzymeExt.jl
- test/enzyme.jl
Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/1075
> Fix enzyme batch mode

- Project.toml
- src/factorization.jl
- test/gpu/cuda.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and
> Fix NormalCholesky on GPU

- .github/workflows/Downstream.yml
- Project.toml
> Add downstream testing for NonlinearSolve

- src/default.jl
Fixes https://github.com/SciML/JumpProcesses.jl/issues/459
> Guard BLAS defaults more, allowing only Array and BLASFloats

- docs/src/advanced/custom.md
> Fix small typo in Readme.md

- ext/LinearSolveEnzymeExt.jl
- test/nopre/enzyme.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/479. I couldn't figure out the nested calls case so I made that error for now.
> Fix direct usage of cache with enzyme

- ext/LinearSolveSparseArraysExt.jl
- test/sparse_vector.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/614
> Fix complex sparse cache dispatches

- ext/LinearSolveBLISExt.jl
- ext/LinearSolveCUDAExt.jl
- ext/LinearSolveMetalExt.jl
- src/LinearSolve.jl
- src/default.jl
Fixes https://github.com/SciML/LinearSolve.jl/issues/790 and https://discourse.julialang.org/t/linearsolvecudaext-fails-to-compile/131693/10
> Fix precompilation of usecuda, usemetal, and useblis

- ext/LinearSolveSparseArraysExt.jl
- src/default.jl
KLU is LGPL so it should be allowed, and don't try to precompile UMFPack if nogpl
> Fix nogpl precompile
